/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.testing.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the KycDetails service. Represents a row in the &quot;Panasonic_KycDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.testing.service.model.impl.KycDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.testing.service.model.impl.KycDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KycDetails
 * @generated
 */
@ProviderType
public interface KycDetailsModel
	extends BaseModel<KycDetails>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kyc details model instance should use the {@link KycDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this kyc details.
	 *
	 * @return the primary key of this kyc details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this kyc details.
	 *
	 * @param primaryKey the primary key of this kyc details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this kyc details.
	 *
	 * @return the uuid of this kyc details
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this kyc details.
	 *
	 * @param uuid the uuid of this kyc details
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the kyc detail ID of this kyc details.
	 *
	 * @return the kyc detail ID of this kyc details
	 */
	public long getKycDetailId();

	/**
	 * Sets the kyc detail ID of this kyc details.
	 *
	 * @param kycDetailId the kyc detail ID of this kyc details
	 */
	public void setKycDetailId(long kycDetailId);

	/**
	 * Returns the group ID of this kyc details.
	 *
	 * @return the group ID of this kyc details
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this kyc details.
	 *
	 * @param groupId the group ID of this kyc details
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this kyc details.
	 *
	 * @return the company ID of this kyc details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this kyc details.
	 *
	 * @param companyId the company ID of this kyc details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this kyc details.
	 *
	 * @return the user ID of this kyc details
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this kyc details.
	 *
	 * @param userId the user ID of this kyc details
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this kyc details.
	 *
	 * @return the user uuid of this kyc details
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this kyc details.
	 *
	 * @param userUuid the user uuid of this kyc details
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this kyc details.
	 *
	 * @return the user name of this kyc details
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this kyc details.
	 *
	 * @param userName the user name of this kyc details
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this kyc details.
	 *
	 * @return the create date of this kyc details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this kyc details.
	 *
	 * @param createDate the create date of this kyc details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this kyc details.
	 *
	 * @return the modified date of this kyc details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this kyc details.
	 *
	 * @param modifiedDate the modified date of this kyc details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the address of this kyc details.
	 *
	 * @return the address of this kyc details
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this kyc details.
	 *
	 * @param address the address of this kyc details
	 */
	public void setAddress(String address);

	/**
	 * Returns the pan number of this kyc details.
	 *
	 * @return the pan number of this kyc details
	 */
	@AutoEscape
	public String getPanNumber();

	/**
	 * Sets the pan number of this kyc details.
	 *
	 * @param panNumber the pan number of this kyc details
	 */
	public void setPanNumber(String panNumber);

	/**
	 * Returns the gstn number of this kyc details.
	 *
	 * @return the gstn number of this kyc details
	 */
	@AutoEscape
	public String getGstnNumber();

	/**
	 * Sets the gstn number of this kyc details.
	 *
	 * @param gstnNumber the gstn number of this kyc details
	 */
	public void setGstnNumber(String gstnNumber);

	/**
	 * Returns the type of business of this kyc details.
	 *
	 * @return the type of business of this kyc details
	 */
	@AutoEscape
	public String getTypeOfBusiness();

	/**
	 * Sets the type of business of this kyc details.
	 *
	 * @param typeOfBusiness the type of business of this kyc details
	 */
	public void setTypeOfBusiness(String typeOfBusiness);

	/**
	 * Returns the address proof ID of this kyc details.
	 *
	 * @return the address proof ID of this kyc details
	 */
	public long getAddressProofId();

	/**
	 * Sets the address proof ID of this kyc details.
	 *
	 * @param addressProofId the address proof ID of this kyc details
	 */
	public void setAddressProofId(long addressProofId);

	/**
	 * Returns the pan proof ID of this kyc details.
	 *
	 * @return the pan proof ID of this kyc details
	 */
	public long getPanProofId();

	/**
	 * Sets the pan proof ID of this kyc details.
	 *
	 * @param panProofId the pan proof ID of this kyc details
	 */
	public void setPanProofId(long panProofId);

	/**
	 * Returns the gstn proof ID of this kyc details.
	 *
	 * @return the gstn proof ID of this kyc details
	 */
	public long getGstnProofId();

	/**
	 * Sets the gstn proof ID of this kyc details.
	 *
	 * @param gstnProofId the gstn proof ID of this kyc details
	 */
	public void setGstnProofId(long gstnProofId);

	/**
	 * Returns the type of business ID of this kyc details.
	 *
	 * @return the type of business ID of this kyc details
	 */
	public long getTypeOfBusinessId();

	/**
	 * Sets the type of business ID of this kyc details.
	 *
	 * @param typeOfBusinessId the type of business ID of this kyc details
	 */
	public void setTypeOfBusinessId(long typeOfBusinessId);

	@Override
	public KycDetails cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}