/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.service.myBlogPosting.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MyBolgPosting service. Represents a row in the &quot;Scheduler_MyBolgPosting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.service.myBlogPosting.model.impl.MyBolgPostingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.service.myBlogPosting.model.impl.MyBolgPostingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MyBolgPosting
 * @generated
 */
@ProviderType
public interface MyBolgPostingModel
	extends BaseModel<MyBolgPosting>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a my bolg posting model instance should use the {@link MyBolgPosting} interface instead.
	 */

	/**
	 * Returns the primary key of this my bolg posting.
	 *
	 * @return the primary key of this my bolg posting
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this my bolg posting.
	 *
	 * @param primaryKey the primary key of this my bolg posting
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this my bolg posting.
	 *
	 * @return the uuid of this my bolg posting
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this my bolg posting.
	 *
	 * @param uuid the uuid of this my bolg posting
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the my blog posting ID of this my bolg posting.
	 *
	 * @return the my blog posting ID of this my bolg posting
	 */
	public long getMyBlogPostingId();

	/**
	 * Sets the my blog posting ID of this my bolg posting.
	 *
	 * @param myBlogPostingId the my blog posting ID of this my bolg posting
	 */
	public void setMyBlogPostingId(long myBlogPostingId);

	/**
	 * Returns the group ID of this my bolg posting.
	 *
	 * @return the group ID of this my bolg posting
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this my bolg posting.
	 *
	 * @param groupId the group ID of this my bolg posting
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this my bolg posting.
	 *
	 * @return the company ID of this my bolg posting
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this my bolg posting.
	 *
	 * @param companyId the company ID of this my bolg posting
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this my bolg posting.
	 *
	 * @return the user ID of this my bolg posting
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this my bolg posting.
	 *
	 * @param userId the user ID of this my bolg posting
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this my bolg posting.
	 *
	 * @return the user uuid of this my bolg posting
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this my bolg posting.
	 *
	 * @param userUuid the user uuid of this my bolg posting
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this my bolg posting.
	 *
	 * @return the user name of this my bolg posting
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this my bolg posting.
	 *
	 * @param userName the user name of this my bolg posting
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this my bolg posting.
	 *
	 * @return the create date of this my bolg posting
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this my bolg posting.
	 *
	 * @param createDate the create date of this my bolg posting
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this my bolg posting.
	 *
	 * @return the modified date of this my bolg posting
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this my bolg posting.
	 *
	 * @param modifiedDate the modified date of this my bolg posting
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the heading of this my bolg posting.
	 *
	 * @return the heading of this my bolg posting
	 */
	@AutoEscape
	public String getHeading();

	/**
	 * Sets the heading of this my bolg posting.
	 *
	 * @param heading the heading of this my bolg posting
	 */
	public void setHeading(String heading);

	/**
	 * Returns the description of this my bolg posting.
	 *
	 * @return the description of this my bolg posting
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this my bolg posting.
	 *
	 * @param description the description of this my bolg posting
	 */
	public void setDescription(String description);

	@Override
	public MyBolgPosting cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}